// Re-export all Supabase functions from services
// This file provides backward compatibility for imports from ./lib/supabase

export {
    supabase,
    signInWithMagicLink,
    signInWithGoogle,
    isEmailAllowed,
    signOut,
    getCurrentUser,
    getPages,
    getPageBySlug,
    getContentByPage,
    getContentByPageAndSection,
    updateContent,
    createContent,
    getPackages,
    updatePackage,
    updatePackageHighlights,
    getMedia,
    getMediaBySection,
    uploadMedia,
    deleteMedia,
    getSettings,
    updateSetting,
    upsertPages,
    // Draft functions - Ticket 5
    getDraftsForSection,
    getDraftByContentId,
    upsertDraft,
    deleteDraft,
    deleteDraftsForPage,
    deleteDraftsForSection,
    type PageUpsert,
} from '../services/supabase';
