// Re-export all Supabase functions from services
// This file provides backward compatibility for imports from ./lib/supabase

export {
    supabase,
    signInWithMagicLink,
    signInWithGoogle,
    isEmailAllowed,
    signOut,
    getCurrentUser,
    getPages,
    getPageBySlug,
    createPage,
    updatePage,
    deletePage,
    getContentByPage,
    getContentByPageAndSection,
    updateContent,
    createContent,
    deleteContent,
    getPackages,
    updatePackage,
    updatePackageHighlights,
    createPackage,
    deletePackage,
    getMedia,
    getMediaBySection,
    uploadMedia,
    deleteMedia,
    updateMediaAltText,
    getSettings,
    updateSetting,
    createSetting,
    deleteSetting,
    upsertPages,
    // Draft functions
    getDraftsForSection,
    getDraftByContentId,
    upsertDraft,
    deleteDraft,
    deleteDraftsForPage,
    deleteDraftsForSection,
    type PageUpsert,
} from '../services/supabase';
